### ISSUE TITLE
E2E tests fail

### ISSUE THREAD

**Issue by omeraha** [lirantal/pie-my-vulns#23]
## Expected Behavior
All E2E tests should pass

## Current Behavior
" CLI should show vulnerabilities breakdown numbers and their titles" test fails:
![image](https://user-images.githubusercontent.com/43315856/75564102-2ef85200-5a54-11ea-9d88-857dfb32bb3e.png)

## Steps to Reproduce (for bugs)

1. run `npm run test:e2e`

**Comment by lirantal** [comment]
@omeraha ahh I know what it is.
my last commit was a change that modified the behavior to not always display the dependency type (production/development) because it's not really always available and then it makes an incorrect assumption.

Can you push a PR that removes lines 39-41 and 46 too? that should fix the tests for the project

**Comment by omeraha** [comment]
@lirantal Can I close this one?

**Comment by lirantal** [comment]
Yep!
