### ISSUE TITLE
Feat: Dockerfile for the project

### ISSUE THREAD

**Issue by lirantal** [lirantal/pie-my-vulns#3]
## Description

To make the CLI more accessible to those without a Node.js environment let's create a Dockerfile that I can push into Docker Hub and allow them to spin off the CLI via a container

**Comment by omeraha** [comment]
I Created the docker file. I have a suggestion: what do you think about using the docker image in the E2E tests, instead of calling pie-my-vulns.js directly? Something like this:
![image](https://user-images.githubusercontent.com/43315856/75613685-3f362d00-5b39-11ea-9f6a-8f28e4a123f9.png)

Then we can run this test suit in the future as part of the CI after building the docker image.

**Comment by lirantal** [comment]
I'm less inclined to do this because those tests are supposed to be able to run for anyone and assuming a docker on every dev environment isn't that friendly. Moreover, on the first run and potentially future runs, the test will need to pull the image which will take some time.

That said, I think we can definitely have a sort of E2E test that runs on the CI part in Pull Requests that will build the docker image, and then test it to make sure it works well before pushing it. There's related work on that already on on the circleci that publishes an npm package and submits it and I think we can extend that in this sense.

**Comment by omeraha** [comment]
Agree. I think even some basic sanity tests on the docker image will do (no need to test the same scenarios we test in the E2E tests all over again). Will create a pull request with the docker image changes lated today.

**Comment by lirantal** [comment]
Perfect 👌

**Comment by omeraha** [comment]
@lirantal Can I close this issue?

**Comment by lirantal** [comment]
Yep!

**Comment by omeraha** [comment]
Docker file was added to the repo
