### ISSUE TITLE
Automatic auth redirection does not work in docker

### ISSUE THREAD

**Issue by omeraha** [lirantal/pie-my-vulns#52]
When running the docker image of pie-my-vulns unauthenticated, the automatic redirection to the authentication page does not work, and the use has to copy-paste the url in the browser in order to authenticate against Snyk.

## Expected Behavior

The browser should open automatically with the url to Snyk authentication page. 

## Current Behavior

Nothing happens.

## Possible Solution

Requires debugging

## Steps to Reproduce (for bugs)

1. Run pie-my-vulns docker image: `docker run pie-my-vulns`
2. Inspect the issue

## Your Environment

- Node.js version (e.g. Node.js 5.4): 12.16.1
- Operating System and version (desktop or mobile): mac OS

**Comment by lirantal** [comment]
True there. I'm not sure how we would be opening the native user's browser from the docker image... The whole idea with containers is to run in an isolated environment, no? To be honest, kind of makes sense to me that a person would copy&paste the link to their browsers to run it.

How about we update the docker image to also receive a snyk api token which it will then use internally to feed into the snyk config file (we can do this as part of the image itself instead of the CLI). WDYT?

**Comment by omeraha** [comment]
@lirantal Sound like the right solution - this will also result in a much better user experience (as the user will not have to even be redirected). How do we generate such a token?

**Comment by lirantal** [comment]
1. Get it from the Snyk UI's Settings page
2. From the CLI, if a user has the Snyk CLI installed: `snyk config get api` should return the API token. On most POSIX systems this is on `~/.config/configstore/snyk.json`

**Comment by omeraha** [comment]
@lirantal Started to take a look at this, and I guess there are two main options here (once we have the token passed to the docker container):

1. Use `snyk auth <token>` command with the token before running `npx pie-my-vulns` command.

1. Add a `--token` arg to `pie-my-vulns` with the token and call the `authenticate()` method before the `test()`  method with the provided token.

WDYT? Which one is the better option IYO?

**Comment by lirantal** [comment]
I think (2) is better because it will be generally useful for outside of docker too. What do you think?

**Comment by omeraha** [comment]
Agreed. I will start working on this soon.
